---

- name: uninstall postfix
  yum:
    name: postfix
    state: absent

- name: Set hosts file
  lineinfile:
    line: "{{ zimbra_public_ip }} {{ zimbra_public_fqdn }}"
    path: /etc/hosts

- name: Install Packages
  yum:
    name: "{{ zimbra_packages }}"

- name: Install PIP Packages
  pip:
    name: "{{ zimbra_pip_packages }}"


- name: Download Zimbra
  get_url:
    url: "{{ zimbra_download_url }}"
    dest: "{{ zimbra_archive_path }}"

- name: Create tmp dir
  file:
    path: "{{ zimbra_tmp_path }}"
    state: directory

- name: Extract Zimbra
  unarchive:
    src: "{{ zimbra_archive_path }}"
    dest: "{{ zimbra_tmp_path }}"
    remote_src: yes

- name: Rename zcs-folder
  shell: test -d {{ zimbra_tmp_path }}/zcs || mv {{ zimbra_tmp_path }}/zcs* {{ zimbra_tmp_path }}/zcs

- name: Generate answer_key-file
  template:
    dest: "{{ zimbra_tmp_path }}/answer_key_file"
    src: templates/answer_key_file.j2

- name: Generate install_config
  template:
    dest: "{{ zimbra_tmp_path }}/install_config"
    src: templates/install_config.j2

- name: Installing Zimbra
  shell: ./install.sh -s < {{ zimbra_tmp_path }}/answer_key_file
  args:
    chdir: "{{ zimbra_tmp_path }}/zcs"

- name: Configuring Zimbra
  command: ./zmsetup.pl -c {{ zimbra_tmp_path }}/install_config
  args:
    chdir: /opt/zimbra/libexec/

- name: Open Firewall Ports (SMTP & Web)
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ zimbra_ports }}"

- name: Open Firewall Ports (IMAP)
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ zimbra_imap_ports }}"
  when: zimbra_openports_imap == true

- name: Open Firewall Ports (POP3)
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ zimbra_pop3_ports }}"
  when: zimbra_openports_pop3 == true

- name: Start Server
  command: zmcontrol restart
  become: yes
  become_user: zimbra
