---
- name: Download Zimbra
  get_url:
    url: "{{ zimbra_download_url }}"
    dest: "{{ zimbra_archive_path }}"

- name: Create tmp dir
  file:
    path: "{{ zimbra_tmp_path }}"
    state: directory

- name: Extract Zimbra
  unarchive:
    src: "{{ zimbra_archive_path }}"
    dest: "{{ zimbra_tmp_path }}"
    remote_src: yes
