---

- name: Set hosts file
  lineinfile:
    line: "{{ zimbra_public_ip }} {{ zimbra_public_fqdn }}"
    path: /etc/hosts

- name: Download Zimbra
  get_url:
    url: "{{ zimbra_download_url }}"
    dest: "{{ zimbra_archive_path }}"

- name: Create tmp dir
  file:
    path: "{{ zimbra_tmp_path }}"
    state: directory

- name: Extract Zimbra
  unarchive:
    src: "{{ zimbra_archive_path }}"
    dest: "{{ zimbra_tmp_path }}"
    remote_src: yes

- name: Rename zcs-folder
  command: mv {{ zimbra_tmp_path }}/zcs* {{ zimbra_tmp_path }}/zcs

#- name: Start install-script
#  expect:
#    command: "{{ zimbra_tmp_path }}/zcs/install.sh"
#    responses:
#      'Do you agree with the terms of the software license agreement(.*)': y

